POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Arto Hellas",
    "number": "12345678"
}
### POST without name
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": "12345678"
}

### POST without number
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Alkaidcc"
}